export * from './country-wise/country-wise.component';
export * from './precautions/precautions.component';
export * from './state-wise/state-wise.component';
export * from './donation/donation.component';
export * from './login/login.component';
export * from './register/register.component';
export * from './navbar/navbar.component';
export * from './slot-viewer/slot-viewer.component';
export * from './admin';